addons:
  apt:
    packages:
    - libxxf86vm-dev
    - libosmesa6-dev
language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
os:
  - osx
  - linux
notifications:
  webhooks: http://build.servo.org:54856/travis
script: cargo build --verbose
